app/models.py
from datetime import datetime

from flask import current_app
from flask_login import UserMixin
from faker import Faker
from sqlalchemy.exc import IntegrityError

from . import db, bcrypt


class AbstractModel(db.Model):
    """An abstract model with basic items required by all models."""
    __abstract__ = True
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)

    def __init__(self, **kwargs):
        self.commit = kwargs.pop('commit', True)
        super().__init__(**kwargs)
        self.add_and_commit()

    def __repr__(self):
        """Return a default __repr__ for all subclasses."""
        return f'<{self.__class__.__name__}: "{self.id}">'

    def add_and_commit(self):
        """Add the record to the session and commit it to the database."""
        if self.commit:
            db.session.add(self)
            try:
                db.session.commit()
            except IntegrityError as error:
                db.session.rollback()
                raise error

    @classmethod
    def count(cls):
        """Return the number of records of this class in the database."""
        return db.session.query(cls.id).count()

    @classmethod
    def select_by_id(cls, id):
        return cls.query.filter_by(id=id).first()


class User(UserMixin, AbstractModel):
    """A simple user model that will support logging into the app."""
    __tablename__ = 'users'

    email = db.Column(db.String(255), unique=True, nullable=False)
    _hash = db.Column(db.String(255), nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)

    def __repr__(self):
        """Override the super class's __repr__ to show the user's email address."""
        return f'<User: "{self.email}">'

    def check_password(self, password):
        """Return True if the given password matches the stored hash."""
        return bcrypt.check_password_hash(self._hash, password)

    @property
    def password(self):
        """Password is not stored, return the hash."""
        return self._hash

    @password.setter
    def password(self, password, commit=True):
        """Hash the given password and store it in the database.

        :param commit: If True, commits the record to the database, defaults to True
        """
        self.commit = commit
        self._hash = bcrypt.generate_password_hash(
                password, current_app.config['BCRYPT_LOG_ROUNDS']
        ).decode('utf-8')
        self.add_and_commit()

    @classmethod
    def select_by_email(cls, email):
        """Return the unique user identified by the email address."""
        return cls.query.filter_by(email=email).first()

    @classmethod
    def create_fake_users(cls, count=100):
        """Create the number of fake users given by count.

        Returns a list of the created users for possible echoing to a cli function.
        """
        users = []
        fake = Faker()
        for _ in range(count):
            email = fake.email()
            password = fake.password()
            users.append((email, password))
            user = cls(email=email, password=password, commit=False)
            db.session.add(user)
        db.session.commit()
        return users

app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo
from flask_babel import lazy_gettext as _l

from .. import constants as const


class ResetPasswordForm(FlaskForm):
    email = StringField(const.FORM_LABEL_EMAIL_ADDRESS, [DataRequired(), Email()])


class PasswordForm(FlaskForm):
    password = PasswordField(_l('Password'), [DataRequired()])
    confirm_password = PasswordField(_l('Confirm Password'), [DataRequired(), EqualTo('password')])


class LoginForm(FlaskForm):
    email = StringField(_l('Email Address'), [DataRequired(), Email()])
    password = PasswordField(_l('Password'), [DataRequired()])

app/__init__.py
from .create_app import create_app, db, bcrypt, mail  # noqa F401
from .models import User  # noqa F401
from .config import DevConfig, TestConfig, ProdConfig  # noqa F401
from .user import LoginForm  # noqa F401

app/main/views.py
from flask import render_template, Blueprint

main_blueprint = Blueprint('main', __name__)


@main_blueprint.route('/')
def home():
    return render_template('main/home.html')

app/user/__init__.py
from .forms import LoginForm, ResetPasswordForm, PasswordForm  # noqa F401

app/user/views.py
from flask import (render_template, Blueprint, url_for, redirect, flash, request, current_app,
                   abort)
from flask_login import login_user, logout_user, login_required
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer
from itsdangerous.exc import BadSignature

from . import LoginForm, ResetPasswordForm, PasswordForm
from .. import mail, User
from .. import constants as const

user_blueprint = Blueprint('user', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(request.form['password']):
            login_user(user)
            flash(const.LOGIN_SUCCESS_MSG, 'success')
            return redirect(url_for('main.home'))
        else:
            flash(const.LOGIN_FAILURE_MSG, 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', title='Please Login', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash(const.LOGOUT_SUCCESS_MSG, 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/reset', methods=['GET', 'POST'])
def reset():
    """Sends a tokenized email link to the user. Fails silently if email doesn't exist."""
    form = ResetPasswordForm()
    if form.validate_on_submit():
        email = form.email.data
        user = User.select_by_email(email=email)
        if user:
            timed_serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
            token = timed_serializer.dumps(email, salt='recovery-token')
            url = url_for('user.reset_with_token', token=token, _external=True)
            body = render_template('email/recover.txt', url=url)
            html = render_template('email/recover.html', url=url)
            msg = Message(body=body, html=html, recipients=[email],
                          subject=const.RESET_EMAIL_SUBJECT)
            mail.send(msg)
        flash(const.RESET_PASSWORD_REQUEST_FLASH, 'success')
        return redirect(url_for('user.login'))
    return render_template('user/reset.html', form=form)


@user_blueprint.route('/reset/<token>', methods=['GET', 'POST'])
def reset_with_token(token):
    """Updates the user's password."""
    timed_serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    try:
        email = timed_serializer.loads(token, salt='recovery-token', max_age=3600)
    except BadSignature:
        abort(404)
    form = PasswordForm()
    if form.validate_on_submit():
        user = User.select_by_email(email=email)
        user.password = form.password.data
        flash(const.RESET_PASSWORD_SUCCESS, 'success')
        return redirect(url_for('user.login'))
    return render_template('user/password.html', form=form)

app/templates/base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>{{ config.APP_NAME }}{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link href="{{url_for('static', filename='styles.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>

  <body>

    {% include 'header.html' %}

    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
              {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}

        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
        <p class="error"><strong>{{ _('Error') }}:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    <br><br>

    {% include 'footer.html' %}

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='javascript.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

app/templates/errors.html
{% extends "base.html" %}
{% block page_title %}- Page Not Found{% endblock %}
{% block content %}

<div class="jumbotron">
    <div class="text-center">
        <h1>{{ err.code }}</h1>
        <p>{{ err.description }}</p>
        <p>{{ _('Go') }}<a href="{{ url_for('main.home') }}">{{ _('home') }}</a>.</p>
    </div>
</div>

{% endblock %}

app/templates/footer.html
<footer>
  <nav class="navbar fixed-bottom navbar-light bg-light">
    <div class="container">
      <small>
        <span>©
          <a href="http://chivalrysoftware.com">Chivalry Software</a>
        </span>
      </small>
    </div>
  </nav>
</footer>

app/templates/header.html
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <!-- Navbar Brand -->
    <a class="navbar-brand" href="{{ url_for('main.home') }}">{{ config.APP_NAME }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Main Navigation -->
      <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.home') }}">{{ _('Home') }}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">{{ _('About') }}</a>
        </li>
      </ul>
      <!-- Login/Logout -->
      <ul class="navbar-nav ml-auto">
          <li class="nav-item">
              {% if current_user.is_authenticated %}
              <a class="nav-link" href="{{ url_for('user.logout') }}">{{ _('Logout') }}</a>
              {% else %}
              <a class="nav-link" href="{{ url_for('user.login') }}">{{ _('Login') }}</a>
              {% endif %}
          </li>
      </ul>
    </div>
  </div>
</nav>

app/templates/main/home.html
{% extends "base.html" %}
{% block content %}

<div>
    <h1>Welcome!</h1>
    <hr><br>
    <p>Add some content here!</p>
</div>

{% endblock %}

app/templates/user/login.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

    <header class="content-header">
        <h1>{{ _('Login') }}</h1>
        <hr><br>
    </header>

    <br>

    <form class="form" role="form" method="post" action="">
        {{ form.csrf_token }}
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, hiddens="only") }}

        <div class="col-lg-4 col-sm-4">
            {{ wtf.form_field(form.email) }}
            {{ wtf.form_field(form.password) }}

            <button class="btn btn-success" type="submit">{{ _('Log In') }}</button>
            <p><a href="{{ url_for('user.reset') }}">{{ _('Forgot Password') }}</a></p>
        </div>
    </form>

{% endblock %}

app/templates/user/password.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

    <header class="content-header">
        <h1>{{ _('Set Password') }}</h1>
        <hr><br>
    </header>

    <br>

    <form class="form" role="form" method="post" action="">
        {{ form.csrf_token }}
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, hiddens="only") }}

        <div class="col-lg-4 col-sm-4">
            {{ wtf.form_field(form.password) }}
            {{ wtf.form_field(form.confirm_password) }}

            <button class="btn btn-success" type="submit">{{ _('Save') }}</button>
        </div>
    </form>

{% endblock %}

app/templates/user/reset.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

    <header class="content-header">
        <h1>Login</h1>
        <hr><br>
    </header>

    <br>

    <form class="form" role="form" method="post" action="">
        {{ form.csrf_token }}
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, hiddens="only") }}

        <div class="col-lg-4 col-sm-4">
            {{ wtf.form_field(form.email) }}

            <button class="btn btn-success" type="submit">Send Recovery Link</button>
        </div>
    </form>

{% endblock %}